### ISSUE TITLE
Issue when make model on domains

### ISSUE THREAD

**Issue by xBigDaddyx** [luchmewep/boilerplate-generator#1]
Hi, i tried to make Companies model using command bg:make:model
but it thrown an error below,
```

file_put_contents(C:\laragon\www\teresa\C:/laragon/www/teresa/domains/Companies/tests\Feature/Models/CompaniesTest.php): Failed to open stream: No such file or directory

  at vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:205
    201▕      * @return int|bool
    202▕      */
    203▕     public function put($path, $contents, $lock = false)
    204▕     {
  ➜ 205▕         return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);
    206▕     }
    207▕
    208▕     /**
    209▕      * Write the contents of a file, replacing it atomically if it already exists.

  1   vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:205

  2   vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:353
      Illuminate\Filesystem\Filesystem::put("C:\laragon\www\teresa\C:/laragon/www/teresa/domains/Companies/tests\Feature/Models/CompaniesTest.php", "<?php

it('has models/companies page', function () {
    $response = $this->get('/models/companies');

    $response->assertStatus(200);
});
")
```
please kindly help, thanks.

**Comment by inforisorse** [comment]
For sure the path in file_put_contents is wrokg

C:\laragon\www\teresa\C:/laragon/www/teresa/domains/Companies/tests\Feature/Models/CompaniesTest.php

duplicated docroot path
also mixing slash and backslash should be avoided

**Comment by luchtech** [comment]
@xBigDaddyx Good day. Sorry for the delayed response. May I know what version of the package is currently installed on your project? Just run `composer show luchavez/boilerplate-generator`.

<img width="799" alt="image" src="https://github.com/luchavez-technologies/boilerplate-generator/assets/26067874/7012c952-9f0b-475d-95c1-d779ce544b0e">

I have no access to a Windows machine as of the moment so I can't debug on my end. If you are available, please visit the Discord community. Just look for the link on the README of the package.

**Comment by luchtech** [comment]
> For sure the path in file_put_contents is wrokg
> 
> C:\laragon\www\teresa\C:/laragon/www/teresa/domains/Companies/tests\Feature/Models/CompaniesTest.php
> 
> duplicated docroot path also mixing slash and backslash should be avoided

This is Windows related issue. I have no issue creating models in Linux and Mac. I thought I had already fixed it but it seems like there are still issues. If you have a Windows machine, can you help by making a PR?

**Comment by luchtech** [comment]
@xBigDaddyx I think this happened during `handleTestCreation` since I made it to always create a test file. The model was created successfully but the test file failed to be generated. To fix this, I now just added a logic wherein all backward slashes are replaced with forward slashes. I can't test if it works since I have no Windows machine so please just use the latest version `1.0.13` and see if it got fixed. If it works, please close the issue. Thanks!

![image](https://github.com/luchavez-technologies/boilerplate-generator/assets/26067874/c5e603aa-3cde-418b-84bf-44f8bd408a88)

**Comment by luchtech** [comment]
@xBigDaddyx The version `1.0.13` is now available for download. Please update your version and please get back here if it now works. Thanks! 😁

**Comment by xBigDaddyx** [comment]
> @xBigDaddyx I think this happened during `handleTestCreation` since I made it to always create a test file. The model was created successfully but the test file failed to be generated. To fix this, I now just added a logic wherein all backward slashes are replaced with forward slashes. I can't test if it works since I have no Windows machine so please just use the latest version `1.0.13` and see if it got fixed. If it works, please close the issue. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/26067874/269282459-c5e603aa-3cde-418b-84bf-44f8bd408a88.png)

hi, sorry for late.
updated to 1.0.13 seems the issue still there.

**Comment by xBigDaddyx** [comment]
> composer show luchavez/boilerplate-generator

![image](https://github.com/luchavez-technologies/boilerplate-generator/assets/10373528/8ffb7546-aff5-4b56-bee4-bf9f83374f57)

**Comment by xBigDaddyx** [comment]
I noticed this one on ExtendedMakeTest command and im tried to dd of an array after calling pest:test and it thrown error.
![image](https://github.com/luchavez-technologies/boilerplate-generator/assets/10373528/2d25678a-4694-4603-b8c1-1e272d2fd019)
![image](https://github.com/luchavez-technologies/boilerplate-generator/assets/10373528/be09015a-9e27-47d6-ba84-48a4563d72ad)

before calling pest:test it should be okay,
![image](https://github.com/luchavez-technologies/boilerplate-generator/assets/10373528/1b1424a6-859a-480b-934e-2e436a585042)
![image](https://github.com/luchavez-technologies/boilerplate-generator/assets/10373528/f3cf61ee-cecd-4840-9241-d9e2d6be4a4c)

**Comment by luchtech** [comment]
@xBigDaddyx Before I start debugging, can you confirm if you have a command "php artisan pest:test"?

**Comment by xBigDaddyx** [comment]
> @xBigDaddyx Before I start debugging, can you confirm if you have a command "php artisan pest:test"?

yes, its ok.
![image](https://github.com/luchavez-technologies/boilerplate-generator/assets/10373528/89209691-7068-45bc-85e5-c5191a7cb0c8)

**Comment by luchtech** [comment]
@xBigDaddyx Can you head over to the Discord community so I can ask questions directly and fix this bug asap? Here's the link: https://discord.gg/MBxxAkQAxx

**Comment by xBigDaddyx** [comment]
yay, its fixed on newest update. thanks
